### PR TITLE
Add maintainers to the README

### PR DESCRIPTION
**Pull request by HanBnrd**
List the current maintainers in the README

### CODE REVIEW

**Comment by HanBnrd** [comment]
@sreekanthkura7 @emiddell are the details correct?

**Comment by emiddell** [comment]
@HanBnrd, I just updated my affiliation.

**Comment by dboas** [comment]
@sreekanthkura7 's affiliation is correct.

The spellcheck is failing.
It seems all of these need to be added to the spell check:
BIFOLD
Benerradi
Eike
IBS
Kura
Middell
Sreekanth

can a maintainer do that? I haven't figured that out yet.

**Review by dboas — APPROVED** [review]
thanks for updating the wordlist.txt

**Review by samuelpowell — APPROVED** [review]

**Pull request merged**
