### PR TITLE
v1.0 release

### PR DESCRIPTION
**Pull request by sstucker**
Version 1.0 is here!

* General clarification of wording throughout the specification.
* Remove sourcePos, detectorPos, and landmarkPos.
* Add wavelengthActual and wavelengthEmissionActual.
* Change stim/data names from attribute to regular dataset.
* Require either 2D or 3D positions, not just 2D.
* Add list of supported aux name values including accel, gyro, magn
* Add datatypes for processed TD moment data.

### CODE REVIEW

**Comment by rob-luke** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by rob-luke** [comment]
FYI @lpollonini

**Comment by lpollonini** [comment]
:clap::clap::clap::clap::clap: :beers::beers::beers::beers::beers:

**Comment by robquant** [comment]
:rocket: :rocket: :rocket: :tada: :tada: :tada:

**Pull request merged**
