### PR TITLE
Add coordinateSystem fields

### PR DESCRIPTION
**Pull request by rob-luke**
## Background

As discussed in #89 there is ambiguity about how to interpret the `source/detectorPos3D` values in SNIRF files, a coordinate system is required to interpret the 3D values. [FieldTrip has an excellent guide to coordinate systems](https://www.fieldtriptoolbox.org/faq/coordsys/).

From the FieldTrip document:

> To understand the coordinate system in which data is expressed, you should consider:
> 
> * What is the definition of the origin of the coordinate system, i.e. where is [0,0,0]?
> * In which directions are the x-, y- and z-axis pointing, i.e. is +x towards the right or towards anterior?
> * In what units are coordinates expressed, i.e. does the number “1” mean 1 meter, 1 centimeter or 1 millimeter?
> * Is the geometry scaled to some template or atlas, or does it still match the individual’s head/brain size?

fNIRS users often come from either an EEG/MEG or MRI background, and the imaging technique has similarities with both fields. So I think the following quote from the FieldTrip guide is also useful to understand the developement/differences between the available coordinate systems. 

> The coordinate systems used in EEG and MEG measurements are usually defined in terms of anatomical landmarks on the outside of the head, such as the nasion, inion and the left and right pre-auricular points...
> 
> The coordinate systems used for imaging methods such as MRI, PET and CT are usually defined in terms of internal brain structures, such as the anterior and posterior commissure. Furthermore, imaging data is sometimes scaled to a specific standard size, e.g., based on the Talairach-Tournoux atlas or one of the templates from the Montreal Neurological Institute (MNI). 

Coordinate systems are complex, as such, I have decided to propose a solution mirroring how [BIDS handles coordinate systems](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html#standard-template-identifiers). The BIDS developers have considered this issue in detail and found a solution that works for both the M/EEG and MRI community, so I think it should work for us too.

## Proposal

Add two new fields `/nirs(i)/probe/coordinateSystem` and `/nirs(i)/probe/coordinateSystemDescription`.

The `coordinateSystem` field can take any of the valid BIDS coordinate system values or "Other". If the value is "Other" them you should describe the system in `coordinateSystemDescription`.

As we already have `/nirs(i)/metaDataTags/LengthUnit`, then we do not need to mirror the BIDS field `CoordinateUnits`.

## Considerations

My understanding is that the SNIRF specification should allow for a broad range of devices from many labs including custom hardware etc. As such, I did not restrict the coordinate systems to just a subset of the EEG, MEG or fMRI specific coordinate systems. Instead, any valid BIDS coordinate system is allowed here from fMRI or from EEG which should provide maximum flexibility for labs with a more image/source space preference as well as labs with a sensor space preference. Further, including the "Other" option will allow any custom coordinate system to be used too, so long as its described in `coordinateSystemDescription`.

These fields have been set to optional presence. Ideally it would be included in all SNIRF files. However, to maintain backwards compatibility the field must be optional.

The aim here is not to align SNIRF with BIDS. But I think the BIDS team have great experience in this problem and we should build off their experience. Additionally, BIDS-fNIRS may not support all possible coordinate systems and instead restrict to a subset. But I think it is appropriate for SNIRF to have a broader range of options than BIDS permits and provide maximum flexibility for advanced users.

## Transition

I think these are the `coordinateSystem` values that existing SNIRF exporters/vendors would implement:
* NIRx: `MNI152Lin` (I am not 100 sure if this is correct, but its some form of this).
* Kernel: `MNE152NLin2009n[Sym|Asym]` ([reference](https://github.com/mne-tools/mne-python/pull/9929#discussion_r741324893))
* MNE: `CapTrak`

### CODE REVIEW

**Comment by rob-luke** [comment]
I have marked this as a draft so it is not accidentally merged before people have a chance to provide feedback.

Pinging @dboas @sstucker @fangq @robertoostenveld @Zahra-M-Aghajan @robquant in case any of you have feedback on this suggestion.

**Comment by sstucker** [comment]
Looks good to me.

I think working towards making it a required field over the coming years is a good idea

> As we already have /nirs(i)/metaDataTags/LengthUnit, then we do not need to mirror the BIDS field CoordinateUnits.

Honestly I have always been a bit confused to not find this definition in /probe. One could imagine copying a probe Group to multiple files and leave the length unit behind unknowingly. I am not necessarily opposed to duplicating it and phasing out the metaDataTag field

**Comment by rob-luke** [comment]
Thanks @sstucker 

> I think working towards making it a required field over the coming years is a good idea

We should start keeping a record of breaking changes such as this that we might like to make in version 2. We could just tag all the issues/PRs that we would consider for V2. In MNE we do this for issues that need backporting. Worth trying?

**Comment by Zahra-M-Aghajan** [comment]
> I have marked this as a draft so it is not accidentally merged before people have a chance to provide feedback.
> 
> Pinging @dboas @sstucker @fangq @robertoostenveld @Zahra-M-Aghajan @robquant in case any of you have feedback on this suggestion.

This looks great to me. Once this is approved and merged, I will go ahead and add this field to our files!
Thanks for initiating this conversation.

**Comment by lpollonini** [comment]
At the risk of being controversial, I would discuss eliminating the option of 2D coordinates in the future SNIRF v2. I think there are enough brain models, software tools and sensing technologies to always place optodes in the their estimated or actual 3D location.

**Comment by forihuelaespina** [comment]
> At the risk of being controversial, I would discuss eliminating the option of 2D coordinates in the future SNIRF v2. I think there are enough brain models, software tools and sensing technologies to always place optodes in the their estimated or actual 3D location.

Agree. At the end of the day, 2D will still be possible to be "simulated" using 0 in any third coordinate.

**Comment by fangq** [comment]
I understand this is a valid request and coordinate system is an important piece of information when interpreting any coordinates in the data, I am just a little bit worried about the approach - i.e. introducing a dependency to another specification (BIDS) that is also actively being updated/developed. 

We have done this before - such as relying on ISO 8601 time format for `/nirs(i)/metaDataTags/MeasurementTime` and `/nirs(i)/metaDataTags/MeasurementDate` (I added this), or the CMIXF-12 standard for `/nirs(i)/aux(j)/dataUnit` (https://github.com/fNIRS/snirf/pull/92), but one key difference is that these previously cited standards are more stable, widely accepted and have existed for a long time.

BIDS, on the other hand, is still an active effort and many formats/conventions are still being developed, added or updated. I don't really know if this will give us the stability that we hoped for. On the other hand, BIDS already referenced SNIRF in BIDS-fNIRS, so doing this will create a cyclic dependency, which is not a good thing to have in any software or document.

I understand that coordinate system in neuroimaging is complex, so if you want to define something that follows the numerous conventions, it will be messy, like the cited BIDS appendix. However, I am wondering, for the sake of making SNIRF a clean, simple, sufficient and self-contained specification (yet, not in conflict with other coordinate system definition), I am wondering if we can propose explicit data fields instead of name based coordinate systems. 

For example, what do we miss if we add two fields: `"Orientation"` and `"CoordinateOrigin"` in either `metadataTags` or `probe` objects?

`Orientation` can be a string made of 3 out of case-insensitive letters "raslpi" for to denote the orientations for x+/y+/z+ directions, such as `"Orientation" : "ras"`.

a more explicit (and easier to read) example of orientation data structure can be found in my [JNIfTI header](https://github.com/NeuroJSON/jnifti/blob/master/JNIfTI_specification.md#orientation-nifti-1-header-pixdim0), in the form of `"Orientation" : {"x":"r", "y":"a",  "z":"s"}`

`CoordinateOrigin` is a simple 1x3 numeric vector. 

If we want, we can also add a scalar `CoordinateScale`.

I suppose there is a 1-to-1 mapping from these data structures to the BIDS coordinate systems, but I consider these data structures more explicit, more stable, and have less room for interpretation/implementation differences.

what do we miss with the above explicit data fields?

**Comment by fangq** [comment]
> At the risk of being controversial, I would discuss eliminating the option of 2D coordinates in the future SNIRF v2. I think there are enough brain models, software tools and sensing technologies to always place optodes in the their estimated or actual 3D location.

Personally, I love 3D, and built most of my tools (meshing, FEM, MC) in 3D, but I also frequently see people still use/report 2-D probes in either analyses or just visualization because of its simplicity. 

3-D analyses, while being accurate, require substantial complexity in tools and computation which may not be widely available (or available but not beginner-friendly). In some cases, some probe design scenarios, such as [large-sized modular probe design](https://www.biorxiv.org/content/10.1101/2021.04.06.438705v1) as performed by our [MOCA toolbox](https://github.com/COTILab/MOCA), may not be easily salable to 3-D due to the sheer size/burden of the computation.

Also, in order to make coordinate warping (mapping 2D probe to 3D head) to work in several pipelines, such as AtlasViewer, we do need a place to store such source information.

again, I am not advocating for 2D, just feel that if there is not much of a burden, giving people a simple 2D probe representation could address some of these community needs - we can just clarify that the default 2D coordinate system is the "native" space and is user-dependent. In most cases, if anyone has to map 2D to 3D, they will define anchors and registration matrices to map to the two spaces.

**Comment by sstucker** [comment]
@lpollonini 

> At the risk of being controversial, I would discuss eliminating the option of 2D coordinates in the future SNIRF v2. I think there are enough brain models, software tools and sensing technologies to always place optodes in the their estimated or actual 3D location.

A good change before removing it entirely would be to REQUIRE sourcePos3D/detectorPos3D and make the 2D version OPTIONAL (and mark it deprecated)

Re: @fangq 

I agree wholeheartedly that a name-based solution to this is not as robust as a quantitative one.

Despite this, I don't see a quantitative solution as a better alternative. SNIRF's novel `Orientation` and `CoordinateOrigin` actually constitute a brand new convention for representing the same information, actually increasing the burden of using our file format, not decreasing it.

cheeky xkcd: https://imgs.xkcd.com/comics/standards.png

I am not familiar with the actual implementation of these coordinate systems, so please correct me if I am wrong and the above is not the case.

I also don't think @rob-luke's proposal necessarily implies a dependency on the BIDS specification. I see this problem as is solved (admittedly inelegantly) so long as the standards users need to implement can be read and written programmatically. BIDS provides a way to do that, @rob-luke proposes we copy it.

Contrary to keeping the SNIRF file format concise: why not both?

**Comment by lpollonini** [comment]
I knew I would stir controversy ;-). Kidding aside, I was simply projecting onto a SNIRF v2 world where the demand for 2D info would be so low not to be needed anymore. However, either because this will reveal to be inaccurate or because v2 will take place earlier than expected, I think preserving 2D info (at least optionally) would still have value.

**Comment by rob-luke** [comment]
@fang I think your criticism that ` i.e. introducing a dependency to another specification (BIDS) that is also actively being updated/developed.` is unjustified. The BIDS specification NEVER breaks backwards compatibility. And it is actively maintained, not actively modified. I think the fact it is maintained is a benefit not a negative. 

I also agree with @sstucker that inventing a new standard of encoding coordinate systems is going to further muddy the waters. Rather than just reusing the existing BIDS standard that has been well considered already. 

The BIDS standard did not invent the ways of encoding the coordinate system. Valid BIDS coordinate systems like `MNIColin27` or `MNI152Lin` already existed. Relying on the BIDS document simply provides a nice formal structure.

The current vendors that export SNIRF already use the standard spaces described in the BIDS specification. So they simply need to set `/nirs(i)/probe/coordinateSystem = MNI152Lin`. Whereas your idea to invent a new way of specifying the coordinates is more complicated and increases overhead on developers.

Finally, I would like to be able to reuse code developed by the BIDS community. They already have established and tested code (in Matlab and python) for handling coordinate systems. So the approach I suggest will require less coding from us.

**Comment by rob-luke** [comment]
> Contrary to keeping the SNIRF file format concise: why not both?

This will massively increase the overhead to SNIRF readers and writers. And provides no extra functionality. If someone has a custom coordinate system they can use the "Other" option. But put simply, people shouldn't be inventing new coordinate systems, there is already too many.

**Comment by sstucker** [comment]
>people shouldn't be inventing new coordinate systems, there is already too many.

This is my perspective. 

The question is how we specify the coordinate systems we intend to support, not how to specify the coordinate system itself, which seems to me to be beyond the scope of SNIRF entirely.

**Comment by fangq** [comment]
>I agree wholeheartedly that a name-based solution to this is not as robust as a quantitative one.
> Despite this, I don't see a quantitative solution as a better alternative. If the novel `Orientation` and `CoordinateOrigin` your propose constitute a brand new convention for representing the same information, we have increased the burden of using our file format substantially.

adding complexity and yet another convention are certainly not the directions I am hoping to go - in spirit, my goal is to seek quantitative data structures that are the actual representations behind those various choices of name-based coordinate systems. The `Orientation` and `CoordinateOrigin` are mere examples for such purpose - and we don't have to use those if we have other more fundamental data records

>I am not familiar with the actual implementation of these coordinate systems, so please correct me if I am wrong and the above is not the case.

neither do I.

a quick read of fieldtrip's functions to convert between coordinate systems 

https://github.com/fieldtrip/fieldtrip/blob/68835fdcb885304369f49f93aa47d08434972079/fileio/private/ft_headcoordinates.m#L158
https://github.com/fieldtrip/fieldtrip/blob/5db3e6ba73a95b03382b0c77e97e46f5777b672c/utilities/ft_convert_coordsys.m#L170

between coordinates, the essential data structure is an Affine matrix (3x4); for defining each coordinate system, it looks like it needs an `origin` and a `{dir.x,dir.y,dir.z}` vector (i.e. orientation).


Re @rob-luke
> I also agree with @sstucker that inventing a new standard of encoding coordinate systems is going to further muddy the waters. Rather than just reusing the existing BIDS standard that has been well considered already.

no, I am no trying to muddy the water - it has already been muddy enough because of these historical legacies of software support and atlases/templates. these coordinate conventions have already made developer's lives difficult enough. all I am hoping to do is to find a way to "unmuddy" it - maybe I am too ambitious.

**Comment by rob-luke** [comment]
> a quick read of fieldtrip's functions to convert between coordinate systems

This is kind of my point, the code already exists and there is an established literature around existing coordinate systems.

> all I am hoping to do is to find a way to "unmuddy" it - maybe I am too ambitious.

I appreciate your ambition. But I fear we may end up in the situation that @sstucker describes, going from 20 to 21 standards.

As a developer, I am averse to having to support another coordinate system encoding method. As a user I am against the idea as I can't easily google what you describe and get detailed information. But if the coordinate space is "Colin27" then there are many resources I can find to help me learn.

How strong is your stance on not implementing my proposal and using your proposed mechanism @fangq ?

**Comment by fangq** [comment]
> This is kind of my point, the code already exists and there is an established literature around existing coordinate systems.

yes and no - yes, for matured systematically developed tools - like fieldtrip, lead-dbs, mne - such code exists but they are complicated, not easily portable, and not all compatible with BIDS - and no, many NIRS software, including HOMER, Brain AnalysER, do not currently support these named coordinate systems and conversions. Adding those coordinate system support and conversions in a systematic way will be a substantial effort (and burden).

> How strong is your stance on not implementing my proposal and using your proposed mechanism @fangq ?

perhaps I should have made my position clear so my comments won't be misread as a requirement - I felt that I've done my parts for SNIRF, and I would be totally happy letting people with more energy, experience and desire to lead and keep SNIRF further evolved. @sstucker and you have been taking the lead in revising the spec, so my intend has always been phasing out my management models, whether you like it or not, and passing it on to you and other active contributors.

That means I will not be actively reading/reviewing all patches, edits, and you do not need to ask for my approval. I still suggest you to consult @dboas for major changes. I am only subscribing to this and perhaps share some of my views because my interests of maintaining the [JSON wrapper of this format](https://github.com/NeuroJSON/jsnirf/blob/master/JSNIRF_specification.md) for my other project.

**Comment by rob-luke** [comment]
> perhaps I should have made my position clear so my comments won't be misread as a requirement 
> That means I will not be actively reading/reviewing all patches, edits, and you do not need to ask for my approval.

I read your position not as a requirement, but a respected opinion. I hope we can still ping you for your experienced opinions. We will give ample time for you (and others) to review PRs if you wish, but it sounds like we won't wait for your explicit approval from now on.

>  many NIRS software, including HOMER, Brain AnalysER, do not currently support these named coordinate systems and conversions.

This is a tad unrelated. But if there is an established coordinate space used in NIRS we should add it to the BIDS list. I will chase this up with @sstucker in a seperate BIDS discussion.

**Comment by sstucker** [comment]
> I hope we can still ping you for your experienced opinions.
Yeah, I lack awareness of the grander scheme of things/I am mostly with these tools rather than application, so definitely need approval from users. I will encourage more users to join this forum

**Comment by rob-luke** [comment]
> I will encourage more users to join this forum

I was quietly happy with the turn out above already, seven opinions might be a new record 🎉 Lets wait and see what David thinks before merging though.

**Comment by rob-luke** [comment]
@sstucker any further thoughts? It would be good to get this (or something else that solves the problem) merged along with #99 and then cut a new release

**Comment by sstucker** [comment]
Let's get this guy merged, I want to double check the code in #99

**Pull request merged**
