### PR TITLE
Define some supported aux channel names

### PR DESCRIPTION
**Pull request by sstucker**
Defining some /nirs(i)/aux(j)/name values for common signals like accelerometer, gyrometers, magnetometeres. These have counterparts in BIDS.

### CODE REVIEW

**Comment by rob-luke** [comment]
Just quickly reading this due to the upcoming release (sorry if this is already clarified).

 Are these names the only valid names for aux channels? Or are these the supported names for this type of data, but custom names are still allowed?

**Comment by dboas** [comment]
I believe custom names are still allowed. But for common aux labels we want to provide a guide of standard names to facilitate those writing analyze packages looking for specific aux channels.

**Comment by rob-luke** [comment]
Perfect

**Comment by MichaelUM** [comment]
I would suggest to make it more specific in the appendix that supported doesn't mean restricted to. This is not clear when reading the v1.0 definition. 

> 
> 
> I believe custom names are still allowed. But for common aux labels we want to provide a guide of standard names to facilitate those writing analyze packages looking for specific aux channels.

**Comment by rob-luke** [comment]
Thanks for the feedback @MichaelUM 
Could you open a PR for this clarification? It may be as simple as a single word or sentence change, whatever is the minimum change to make this clear.

**Pull request merged**
