### PR TITLE
Add Cortivision to SNIRF compatible vendors

### PR DESCRIPTION
**Pull request by cortivision**

### CODE REVIEW

**Comment by rob-luke** [comment]
Hi @cortivision 

Thanks for the pull request and it's wonderful to see you are exporting data in SNIRF format. Is there somewhere we can download a sample snirf file that is output by your hardware/software?

**Comment by cortivision** [comment]
Hi @rob-luke ,
Please, see the attached file [cortivision_example_snirf.zip](https://github.com/fNIRS/snirf/files/7792517/cortivision_example_snirf.zip)

**Comment by cortivision** [comment]
Also, example from the website https://www.cortivision.com/wp-content/uploads/2021/06/Sample-data-Finger-Tapping-Test-20210608T144233Z-001.zip

**Comment by rob-luke** [comment]
Thanks @cortivision,
I took the liberty of adding "cortivision" to the allowed words list, and now the CI's pass.

------------------

On another note, the SNIRF files you shared do not pass the `pysnirf2` validator (see #95). I have pasted the error below for you convenience.

This raises a larger question (maybe I should open a seperate issue), should we only list on the front page vendors and software that export valid SNIRF files @dboas @sstucker ? We list other software such as nirs-toolbox that does not export valid SNIRF files. For that reason, I think we should add cortivision to stay consistent. Once the pysnirf2 validator is complete, maybe announce a several month cycle to give developers time to fix issues in their files and then remove any invalid software from the front page? 

```python
In [1]: import pysnirf2

In [2]: v, r = pysnirf2.validateSnirf("/Users/rluke/Desktop/FT_sample.snirf")

In [3]: v
Out[3]: False

In [4]: r.display()
<pysnirf2.pysnirf2.ValidationResult object at 0x109f93730>
/nirs/data1/measurementList1/dataTypeIndex            WARNING INDEX_OF_ZERO
/nirs/data1/measurementList1/moduleIndex              WARNING INDEX_OF_ZERO
/nirs/data1/measurementList2/dataTypeIndex            WARNING INDEX_OF_ZERO
/nirs/data1/measurementList2/moduleIndex              WARNING INDEX_OF_ZERO
/nirs/aux1/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
/nirs/aux2/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
/nirs/aux3/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
/nirs/aux4/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
/nirs/aux5/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
/nirs/aux6/timeOffset                                 FATAL   INVALID_DATASET_SHAPE
//__DATA_TYPES__                                      WARNING UNRECOGNIZED_GROUP

Found 53 OK      (hidden)
Found 28 INFO    (hidden)
Found 5 WARNING
Found 6 FATAL

File is INVALID
```

**Review by rob-luke — APPROVED** [review]

**Comment by cortivision** [comment]
Thanks @rob-luke for checking.
We tested the files by importing it in MNE, Homer3 etc. We didn't know about `pysnirf2`.
We will fix our exporter to pass `pysnirf2` validation and then send you updated example .snirf file.

**Comment by rob-luke** [comment]
> We didn't know about pysnirf2.

Yes we need to get better at advertising the available tools and get #95 merged.

> We will fix our exporter to pass pysnirf2 validation and then send you updated example .snirf file.

Cool, and please let us know when that's done. But I dont think that should block this PR, other software that is on the front page have much more egregious errors.

> We tested the files by importing it in MNE

I will add your test file to the MNE testing dataset to ensure that we continue to support files exported by you.

**Comment by cortivision** [comment]
@rob-luke 
We have fixed our export function and new .snirf files are now passing pysnirf2 validation.
Example file: https://www.cortivision.com/wp-content/uploads/2022/01/Sample-data-Finger-Tapping-Test.zip
```python
>>> import pysnirf2
>>> v, r = pysnirf2.validateSnirf("./FT_sample.snirf")
>>> v
True
>>> r.display()
<pysnirf2.pysnirf2.ValidationResult object at 0x7f50fe24a8e0>

Found 60 OK      (hidden)
Found 31 INFO    (hidden)
Found 0 WARNING
Found 0 FATAL  

File is VALID
```

**Comment by sstucker** [comment]
Hi @cortivision-- yes, we'll get this merged regardless. Great you're using the pysnirf2 validator.

I've just released pysnirf2==0.4.0 which fixes some issues with the validator. A big issue we have run into is files with numeric fields saved as arrays of size 1 rather than single values--I think because it is the default behavior of the HDF5 MATLAB interface--but this affects read implementations so we are making an effort to standardize. Many of our internal MATLAB scripts will need to be fixed. So try running the validator again after updating `pip install pysnirf2==0.4.0`

**Pull request merged**
