### PR TITLE
Added ICNNA to snirf supporting software list

### PR DESCRIPTION
**Pull request by forihuelaespina**
Added ICNNA to snirf supporting software list

### CODE REVIEW

**Comment by forihuelaespina** [comment]
With my apologies for the delay. This has now been attended.

**Comment by samuelpowell** [comment]
@forihuelaespina unsure why this is failing, but there is extraneous whitespace at the end of your addition to the wordlist. Could you update (and just in case, leave e.g. a trailing newline if one was present on master).

**Comment by Horschig** [comment]
> ~@forihuelaespina unsure why this is failing, but there is extraneous whitespace at the end of your addition to the wordlist. Could you update (and just in case, leave e.g. a trailing newline if one was present on master).~
> 
> Disregard above. I do not know why this is not passing, any ideas?

Not sure, the trailing white space is the only thing that would come to mind also.

**Comment by forihuelaespina** [comment]
I've now removed the trailing space but left the trailing lines just in case. Whether this is what is preventing the update or not, I do not know.

**Review by samuelpowell — APPROVED** [review]

**Review by rob-luke — APPROVED** [review]
Wonderful, thanks @forihuelaespina

**Pull request merged**
