### PR TITLE
Create SNIRF_H5dump

### PR DESCRIPTION
**Pull request by huppertt**
This is the formated output of the H5dump command on the example snirf file.

### CODE REVIEW

**Comment by fangq** [comment]
@huppertt, 3 minor requests

1. any chance to make the sample file smaller? there is no need to pack a ~4MB sample file with the specs if the purpose is to simply show the structure, not for analyzing the data itself.
2. can you move the two files into a subfolder, say "sample"? just to make it easier to organize
3. can you add a suffix ".txt" to the h5dump output? without the suffix, github can not display the content.

after change, please update this pull request or push another one.
thanks

**Comment by fangq** [comment]
Ted and Jay, I am closing this for now. I will let you guys work out the parser compatibility. 
Also, it seems that most of us agree to create small but varieties of sample files in a separate folder or repo.

**Comment by dboas** [comment]
I just saw again the comment about large sample files.
I’ve been using google team drive, which we’ve got through BU with unlimited space (?), to create shareable links that I think put into github readme.md to point to the large files.
We can do that same thing here.

**Comment by fangq** [comment]
The best way to do this is to create a separate git repository for sample data, and then link it to the specification repo using git submodule. This way, if you just git clone github/snirf, you will get the specification files, and if you add --recursive after clone, you will get both the specs and the sample data. I've used it a lot in my projects.

**Comment by dboas** [comment]
This sounds good.
Also, I realize that the sample files for this purpose don’t really need lots of time series data and thus hopefully we can keep them small enough to fit on github

**Pull request closed without merging**
