### PR TITLE
Add dataOffset field

### PR DESCRIPTION
**Pull request by rob-luke**
As part of understanding the implications of the simpler proposal from @dboas in #126, I wrote out how it might be implemented. (I always lean into the simple solution first and understand its drawbacks before moving to the more complex option).

* Will this resolve the issue raised by @julien-dubois-k ?
* Will it have any downstream undesired effects?
* Would the more complex proposal solve any real-world issues in current or next-gen commercial hardware?

### CODE REVIEW

**Comment by samuelpowell** [comment]
Confirmed as a 'good idea' in meeting of May 24, @rob-luke to convert to full PR for review.

**Comment by julien-dubois-k** [comment]
This seems to address the issue, and does so very simply. Anything preventing this from being completed/merged?

**Comment by samuelpowell** [comment]
@julien-dubois-k the intention is to proceed with this as soon as possible, @rob-luke I am happy to review when you are ready.

**Comment by rob-luke** [comment]
> This seems to address the issue, and does so very simply.
Great to hear, thanks for reviewing @julien-dubois-k  Lets get this issue closed off!

@samuelpowell I've removed the draft status and it's ready for review

**Review by samuelpowell — APPROVED** [review]

**Review by dboas — APPROVED** [review]

**Pull request merged**
