### PR TITLE
add OBELAB to supported vendors

### PR DESCRIPTION
**Pull request by JMKIM-OBELAB**
Dear Collaborators,

We have recently released measurement tool and analysis tool fully compatible to snirf format using NIRSIT system. 

I added OBELAB as a vendor supporting snirf data format.

If there's further information needed, I am happy support.

### CODE REVIEW

**Comment by HanBnrd** [comment]
Thank you @JMKIM-OBELAB.

I've updated the word list to pass spell check tests.

@fNIRS/snirf_maintainers, do we need to test this with the validator?

**Review by hsnam-OBELAB — APPROVED** [review]

**Comment by Horschig** [comment]
> Thank you @JMKIM-OBELAB.
> 
> I've updated the word list to pass spell check tests.
> 
> @fNIRS/snirf_maintainers, do we need to test this with the validator?

Do you mean testing their OBELAB files with the validator? No, we never did this with any other vendor, also not with us.

Or do you mean checking if the repo is still intact? The [spellcheck action](https://github.com/fNIRS/snirf/actions/runs/11152987399/job/30999667514?pr=159) should have checked that. So I think everything is fine here.

**Comment by HanBnrd** [comment]
Yes, I was wondering if we should check vendor files before adding as supported in the specs.

Alright sounds good then.

**Review by HanBnrd — APPROVED** [review]

**Comment by Horschig** [comment]
I think it's the vendor's responsibility to check whether their files really conform to the specs, it should not be our task (also e.g. in our case there are 100s of possible file types, like single device, multiple devices, with aux channels, without, etc, so it's a Herculean task without known device details).

**Pull request merged**
